#! /usr/bin/env ruby

# Copyright (c) 2021-2024,2026 David H. Hovemeyer <david.hovemeyer@gmail.com>
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included
# in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR
# OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
# ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR

# Generate grammar_symbols.h and grammar_symbols.cpp from grammar productions
# in parse.y and the AST node types in include/ast.h

if ARGV.length != 2
  STDERR.puts "Usage: scan_grammar_symbols.rb <parser spec> <ast header>"
  exit 1
end

parser_spec_filename = ARGV[0]
ast_header_filename = ARGV[1]

print "Generating grammar_symbols.h/grammar_symbols.cpp..."
STDOUT.flush

# bison token types start at 258
TOKEN_START = 258
# Integer ordinal value of first nonterminal symbol
NONTERM_START = 1000
# AST node orginal values start at 10000
AST_START = 10000

first = true
node_kind_names = []
num_nonterms = 0
first_token = true
num_tokens = 0
num_ast_types = 0

# All generated source and header files go in the "build" directory
header_fh = File.open('build/node_kind.h', 'w')
source_fh = File.open('build/node_kind.cpp', 'w')

header_fh.print <<"EOF1"
#ifndef NODE_KIND_H
#define NODE_KIND_H

//! @file
//! This header defines the NodeKind enumeration, which defines
//! members for each symbol (terminal and nonterminal) used in the
//! grammar, as well as all of the AST node types. These values
//! are used as tags for the parse tree or AST. It also defines
//! the `node_tag_to_string` function which converts a NodeKind
//! value to a string (useful for printing a textual representation
//! of a ndoe or tree.)

//! NodeKind enumeration.
enum NodeKind {
EOF1

File.open(parser_spec_filename, 'r') do |parser_spec_in|
  parser_spec_in.each_line do |line|
    if m = line.match(/^([a-z_]+)(\s*\/\*.*|\s+)?$/)
      # Nonterminal names are prefixed with NODE_, mostly just
      # because they would be all lower case, which is unexpected
      # for an enumeration member. It doesn't really matter,
      # since nearly_cc builds ASTs which never contain nodes
      # tagged with a nonterminal symbol.
      node_kind_names.push(m[1])
      header_fh.print "  NODE_#{m[1]}"
      header_fh.print " = #{NONTERM_START}" if first
      header_fh.puts ","
      first = false
      num_nonterms += 1
    elsif m = line.match(/^%token(.*)/)
      line = m[1] # skip "%token" at beginning of line

      idx = line.index('>')
      if !idx.nil?
        # A type (%union member) was specified for these tokens,
        # skip to the actual token names
        line = line[idx+1..line.length-1].strip
      end

      line.split(/\s+/).each do |token|
        # Token kinds are prefixed with NODE_ to avoid conflicting
        # with the token names generated by bison in parse.tab.h
        node_kind_names.push(token)
        header_fh.print "  NODE_#{token}"
        header_fh.print " = #{TOKEN_START}" if first_token
        header_fh.puts ","
        first_token = false
        num_tokens += 1
      end
    end
  end
end

first_ast_type = true
File.open(ast_header_filename, 'r') do |ast_header_in|
  ast_header_in.each_line do |line|
    if m = /^\s*(AST_\S+)(\s*=\s*\d+)?\s*,/.match(line)
      ast_type = m[1]
      node_kind_names.push(ast_type)
      header_fh.print "  #{ast_type}"
      header_fh.print " = #{AST_START}" if first_ast_type
      header_fh.puts ","
      first_ast_type = false
      num_ast_types += 1
    end
  end
end

header_fh.print <<"EOF2"
};

//! Get grammar symbol name corresponding to tag (enumeration value).
//! Useful for making sense of a parse tree node based on its tag value.
//! Note that this function doesn't return anything useful for AST
//! node tags, since they don't appear directly in the grammar.
//!
//! @param tag a GrammarSymbol value
//! @return a string with a textual representation of the GrammarSymbol
const char *get_grammar_symbol_name(NodeKind tag);

#endif // NODE_KIND_H
EOF2

source_fh.print <<"EOF3"
#include "node_kind.h"

namespace {
const char *s_node_kind_names[] = {
EOF3
node_kind_names.each do |name|
  source_fh.puts "  \"#{name}\","
end

source_fh.print <<"EOF4"
};
}

const char *get_grammar_symbol_name(NodeKind tag) {
  if (tag < #{TOKEN_START}) {
    return nullptr;
  }

  if (tag < #{NONTERM_START}) {
    // must be a token
    int which_token = int(tag) - #{TOKEN_START};
    if (which_token >= #{num_tokens}) {
      return nullptr;
    } else {
      return s_node_kind_names[which_token];
    }
  }

  if (tag < #{AST_START}) {
    // must be a nonterminal
    int which_nonterm = int(tag) - #{NONTERM_START};
    if (which_nonterm >= #{num_nonterms}) {
      return nullptr;
    }
    return s_node_kind_names[#{num_tokens} + which_nonterm];
  }

  // must be an AST node type
  int which_ast_type = int(tag) - #{AST_START};
  if (which_ast_type > #{num_ast_types})
    return nullptr;
  return s_node_kind_names[#{num_tokens} + #{num_nonterms} + which_ast_type];
}
EOF4

header_fh.close
source_fh.close

puts "Done!"
